Repository emory-libraries/dlp-selfdeposit, pull requests merged in 2024-05, with the labels that each got.

#255 Creates a custom query to pull a work's parent work.
  app/services/hyrax/listeners/member_cleanup_listener.rb
  app/services/self_deposit/custom_queries/find_parent_works.rb
  config/initializers/hyrax.rb
Labels: bug, Backend

#256 Makes visibility 'open' (Public) by default in the form.
  app/controllers/hyrax/publications_controller.rb
Labels: enhancement, Backend

#259 Reworks and refactors our custom queries.
  app/services/self_deposit/custom_queries/find_parent_works.rb
  app/services/self_deposit/custom_queries/find_publication_by_deduplication_key.rb
  spec/importers/preservation_workflow_importer_spec.rb
Labels: enhancement, Backend

#270 Restarts the server only after the branch/commit history is logged.
  config/deploy.rb
Labels: bug, Backend

#271 Adds switch to creator partial that uses default behavior if controller is anything but Publication.
  app/views/records/edit_fields/_creator.html.erb
Labels: bug, Backend

#272 Adds desired fields to Collection.
  app/forms/collection_resource_form.rb
  app/indexers/collection_resource_indexer.rb
  app/models/collection_resource.rb
  config/metadata/collection_resource.yaml
  config/metadata/emory_basic_metadata.yaml
  config/metadata/publication_metadata.yaml
  spec/forms/collection_resource_form_spec.rb
  spec/models/collection_resource_spec.rb
  spec/models/collection_spec.rb
  spec/models/hyrax/file_metadata_spec.rb
  spec/support/shared_examples_for_models.rb
Labels: enhancement, Backend

#274 Removes unnecessary fields from Collection's form.
  app/forms/collection_resource_form.rb
  config/metadata/collection_resource.yaml
  spec/forms/collection_resource_form_spec.rb
Labels: enhancement, Backend

#279 Moves attributes that shouldn't appear in Collections to Publication-specific YAML.
  app/forms/generic_work_form.rb
  app/models/generic_work.rb
  config/metadata/emory_basic_metadata.yaml
  config/metadata/publication_metadata.yaml
  spec/models/collection_resource_spec.rb
Labels: bug, Backend

#296 Fix visibility prompt bug
  .rubocop.yml
  app/controllers/concerns/hyrax/works_controller_behavior.rb
Labels: Backend

#301 Adds the desired fields to the Publication show page.
  app/controllers/catalog_controller.rb
  app/views/hyrax/base/_attribute_rows.html.erb
  config/metadata/emory_basic_metadata.yaml
  config/metadata/publication_metadata.yaml
  spec/views/hyrax/base/_attribute_rows.html.erb_spec.rb
Labels: enhancement, Backend

#315 Eliminates ownership error affecting linux users.
  config/initializers/footer.rb
Labels: bug

#316 Adds additional internal predicates missing from Hyrax.
  config/metadata/emory_internal_metadata.yaml
Labels: enhancement, Backend
